server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jc.jdbc.Driver
    url: jdbc:mysql://192.168.43.14:3306/fooddb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
      show-sql: true
      hbm2ddl:
        jdbc_metadata_extraction_strategy: individually