server:
  port: 8082
spring:
  datasource:
    url: '${MYSQL_CI_URL}'
    username: '${MYSQL_USER}'
    password: '${MYSQL_PASSWORD}'
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
      show-sql: true
      hbm2ddl:
        jdbc_metadata_extraction_strategy: individually