version: '3'
services:
  user-app:
    image: user-app
    build: userservice/
    restart: always
    network_mode: host
    ports:
      - 8089:8089
    expose:
      - 8089
    depends_on:
      - foodapp-mysql
  favourite-app:
    image: fav-app
    build: favouriteservice/
    restart: always
    network_mode: host
    ports:
     - 8082:8082
    expose:
     - 8082
    depends_on:
     - foodapp-mysql
  foodapp-mysql:
    image: mysql:5.5
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: foodDB
  angular:
    image: angular-image
    build: NutritionistUI/
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
    expose:
      - 4200