version: '3'
services:
  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodDB
      MYSQL_USER_NAME: app_root
      MYSQL_PASSWORD: root123
  userapp:
    image: anishajayaraj/nutritionist:user-service-image
    restart: always
    network_mode: host
    container_name: userapp-docker
    depends_on:
      - movie-mysql
    ports:
      - 8089:8089
  favouriteapp:
    image: anishajayaraj/nutritionist:fav-service-image
    restart: always
    network_mode: host
    container_name: favouriteapp-docker
    depends_on:
      - movie-mysql
    ports:
      - 8082:8082
  angular:
    image: anishajayaraj/nutritionist:angular-image
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200