image: maven:3-jdk-8
before_script:
  - source ./env-variable.sh
stages:
  - test
  - build
services:
  - 'mysql:latest'
variables:
  MYSQL_DATABASE: fooddb
  MYSQL_CI_URL:  jdbc:mysql://localhost:3306/fooddb?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: password
cache:
  paths:
    - .m2/repository/
    - target
maven-test:
  stage: test
  script: 'mvn test -B'
maven-build:
  stage: build
  script: 'mvn package -U'
  artifacts:
    paths:
      - 'target/*.jar'