server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
      show-sql: true
      hbm2ddl:
        jdbc_metadata_extraction_strategy: individually